apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: security-app
  namespace: restaurant
spec:
  hostname: "mandialand.com"
  prefix: /securityApi/
  service: security-app.restaurant:3001
